export const QUOTATION_CREATE_REQUEST = 'QUOTATION_CREATE_REQUEST'
export const QUOTATION_CREATE_SUCCESS = 'QUOTATION_CREATE_SUCCESS'
export const QUOTATION_CREATE_FAIL = 'QUOTATION_CREATE_FAIL'
export const QUOTATION_CREATE_RESET = 'QUOTATION_CREATE_RESET'

export const QUOTATION_VIEW_ALL_REQUEST = 'QUOTATION_VIEW_ALL_REQUEST'
export const QUOTATION_VIEW_ALL_SUCCESS = 'QUOTATION_VIEW_ALL_SUCCESS'
export const QUOTATION_VIEW_ALL_FAIL = 'QUOTATION_VIEW_ALL_FAIL'

export const QUOTATION_GET_BY_ID_REQUEST = 'QUOTATION_GET_BY_ID_REQUEST'
export const QUOTATION_GET_BY_ID_SUCCESS = 'QUOTATION_GET_BY_ID_SUCCESS'
export const QUOTATION_GET_BY_ID_FAIL = 'QUOTATION_GET_BY_ID_FAIL'
